-keep class tv.danmaku.ijk.** { *; }
-keep class com.shuyu.gsyvideoplayer.** { *; }
-keep class com.alivc.**{*;}
-keep class com.aliyun.**{*;}
-keep class com.cicada.**{*;}
-dontwarn com.alivc.**
-dontwarn com.aliyun.**
-dontwarn com.cicada.**